version: '3.8'
services:
  ollama:      
    image: ollama/ollama
    container_name: ollama
    mem_limit: 10g 
    ports:
      - "11434:11434"
    volumes: 
      - ollama_data:/root/.ollama 
    networks:
      - app-network
    restart: unless-stopped 
    

  backend:
    build:
      context: ./chatfuria
      dockerfile: ../Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - app-network
    restart: unless-stopped

volumes:
  ollama_data:  # Volume persistente para os modelos do Ollama

networks:
  app-network:
    driver: bridge